spring:
  datasource:
    url: jdbc:postgresql://209.135.168.10:5432/postgres
    username: postgres
    password: Y^r3#*f3w*hEAY
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    enabled: true
server:
  error:
    include-message: always
  port: 7777

jwt:
  secretKey: 35b7ce1a67f811e670e8574880be67a68f4cbe9e068d7a747ab0c1614d620d9e
  tokenExpirationHours: 24
