name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo su
            cd /home
            if [ -f "/tmp/pid.file" ]; then
              sudo kill $(cat /tmp/pid.file)
              sudo rm /tmp/pid.file
            fi
            sudo rm -rf fit-app-v5
            sudo git clone https://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@github.com/veccv/fit-app-v5
            cd fit-app-v5
            sudo ./gradlew bootRun &
            echo $! > /tmp/pid.file
            disown
