name: Docker Image CI

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update db url
        run: sed -i 's#<DB_URL>#${{ secrets.DB_URL }}#' src/main/resources/application.yml

      - name: Update db username
        run: sed -i 's#<DB_USERNAME>#${{ secrets.DB_USERNAME }}#' src/main/resources/application.yml

      - name: Update db password
        run: sed -i 's@<DB_PASSWORD>@${{ secrets.DB_PASSWORD }}@' src/main/resources/application.yml

      - name: Update jwt key
        run: sed -i 's#<JWT_SECRETKEY>#${{ secrets.JWT_SECRETKEY }}#' src/main/resources/application.yml

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t docker.pkg.github.com/veccv/fit-app-v5/fitapp-dev:0.0.1 .
          docker push docker.pkg.github.com/veccv/fit-app-v5/fitapp-dev:0.0.1